name: Build results

on:
  push:
    branches:
      - "main"

jobs:

  run_benchmarks:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'ubuntu-22.04', 'windows-2016', 'windows-2019', 'windows-2022']
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Benchmarks
        run: |-
          asv machine --machine ${{ matrix.os }} --yes
          asv run HASHFILE:commits.txt
      - name: Move results(windows)
        if: ${{ matrix.os=='windows-2016' || matrix.os=='windows-2019' || matrix.os=='windows-2022'}}
        run: |
          if(!( test-path ci-results/results/${{ matrix.os }} )) { mkdir ci-results/results/${{ matrix.os }} }
          move-item -path results/${{ matrix.os}}/*.* ci-results/results/${{ matrix.os }}/ -force
          move-item -path results/benchmarks.json ci-results/results/ -force
      - name: Move results(ubuntu)
        if: ${{ matrix.os=='ubuntu-18.04' || matrix.os=='ubuntu-20.04' || matrix.os=='ubuntu-22.04'}}
        run: |
          mkdir -p ci-results/results/${{ matrix.os}}/
          mv -f results/${{ matrix.os}}/*.* ci-results/results/${{ matrix.os}}/
          mv -f results/benchmarks.json ci-results/results/
      - name: Commit results
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github actions bot
          message: 'results for ${{ matrix.os }} added [skip ci]'
          pull: '--rebase --autostash'
